export const CONSECUTIVE_WINS_CONFIG = {
  x1_default: {
    iconAsset: 'glyph_x1_brown',
    icon: { x: -1, y: -1, w: -1, h: -1 },
    iconScale: 1,
    iconRotation: 0,
  },
  x1_active: {
    iconAsset: 'glyph_x1_gold',
    icon: { x: -1, y: -1, w: -1, h: -1 },
    iconScale: 1,
    iconRotation: 0,
  },
  x2_default: {
    iconAsset: 'glyph_x2_brown',
    icon: { x: -1, y: -1, w: -1, h: -1 },
    iconScale: 1,
    iconRotation: 0,
  },
  x2_active: {
    iconAsset: 'glyph_x2_gold',
    icon: { x: -1, y: -1, w: -1, h: -1 },
    iconScale: 1,
    iconRotation: 0,
  },
  x3_default: {
    iconAsset: 'glyph_x3_brown',
    icon: { x: -1, y: -1, w: -1, h: -1 },
    iconScale: 1,
    iconRotation: 0,
  },
  x3_active: {
    iconAsset: 'glyph_x3_gold',
    icon: { x: -1, y: -1, w: -1, h: -1 },
    iconScale: 1,
    iconRotation: 0,
  },
  x5_default: {
    iconAsset: 'glyph_x5_brown',
    icon: { x: -1, y: -1, w: -1, h: -1 },
    iconScale: 1,
    iconRotation: 0,
  },
  x5_active: {
    iconAsset: 'glyph_x5_gold',
    icon: { x: -1, y: -1, w: -1, h: -1 },
    iconScale: 1,
    iconRotation: 0,
  },
  // Auto-spin mode multipliers (x2, x4, x6, x10)
  x2_auto_default: {
    iconAsset: 'glyph_x2_brown',
    icon: { x: -1, y: -1, w: -1, h: -1 },
    iconScale: 1,
    iconRotation: 0,
  },
  x2_auto_active: {
    iconAsset: 'glyph_x2_gold',
    icon: { x: -1, y: -1, w: -1, h: -1 },
    iconScale: 1,
    iconRotation: 0,
  },
  x4_auto_default: {
    iconAsset: 'glyph_x4_red',
    icon: { x: -1, y: -1, w: -1, h: -1 },
    iconScale: 1,
    iconRotation: 0,
  },
  x4_auto_active: {
    iconAsset: 'glyph_x4_gold',
    icon: { x: -1, y: -1, w: -1, h: -1 },
    iconScale: 1,
    iconRotation: 0,
  },
  x6_auto_default: {
    iconAsset: 'glyph_x6_red',
    icon: { x: -1, y: -1, w: -1, h: -1 },
    iconScale: 1,
    iconRotation: 0,
  },
  x6_auto_active: {
    iconAsset: 'glyph_x6_gold',
    icon: { x: -1, y: -1, w: -1, h: -1 },
    iconScale: 1,
    iconRotation: 0,
  },
  x10_auto_default: {
    iconAsset: 'glyph_x10_red',
    icon: { x: -1, y: -1, w: -1, h: -1 },
    iconScale: 1,
    iconRotation: 0,
  },
  x10_auto_active: {
    iconAsset: 'glyph_x10_gold',
    icon: { x: -1, y: -1, w: -1, h: -1 },
    iconScale: 1,
    iconRotation: 0,
  },
  page_title: {
    iconAsset: 'glyph_1024_ways_text',
    icon: { x: -1, y: -1, w: -1, h: -1 },
    iconScale: 0.72,
    iconRotation: 0,
  },
  bg_01: {
    iconAsset: 'background_vertical_coins',
    icon: { x: -1, y: -1, w: -1, h: -1 },
    iconScale: 0.7,
    iconRotation: -Math.PI / 2,
  },
  bg_02: {
    iconAsset: 'background_vertical_wood',
    icon: { x: -1, y: -1, w: -1, h: -1 },
    iconScale: 1,
    iconRotation: -Math.PI / 2,
  },
  bg_03: {
    iconAsset: 'background_top_icons',
    icon: { x: -1, y: -1, w: -1, h: -1 },
    iconScale: 1,
    iconRotation: 0,
  },
};
