export const CONSECUTIVE_WINS_CONFIG = {
  x1_default: {
    iconAsset: 'i65_x1',
    icon: { x: -1, y: -1, w: -1, h: -1 },
    iconScale: 1,
    iconRotation: 0,
  },
  x1_active: {
    iconAsset: 'i64_x1',
    icon: { x: -1, y: -1, w: -1, h: -1 },
    iconScale: 1,
    iconRotation: 0,
  },
  x2_default: {
    iconAsset: 'i65_x2',
    icon: { x: -1, y: -1, w: -1, h: -1 },
    iconScale: 1,
    iconRotation: 0,
  },
  x2_active: {
    iconAsset: 'i64_x2',
    icon: { x: -1, y: -1, w: -1, h: -1 },
    iconScale: 1,
    iconRotation: 0,
  },
  x3_default: {
    iconAsset: 'i65_x3',
    icon: { x: -1, y: -1, w: -1, h: -1 },
    iconScale: 1,
    iconRotation: 0,
  },
  x3_active: {
    iconAsset: 'i64_x3',
    icon: { x: -1, y: -1, w: -1, h: -1 },
    iconScale: 1,
    iconRotation: 0,
  },
  x5_default: {
    iconAsset: 'i65_x5',
    icon: { x: -1, y: -1, w: -1, h: -1 },
    iconScale: 1,
    iconRotation: 0,
  },
  x5_active: {
    iconAsset: 'i64_x5',
    icon: { x: -1, y: -1, w: -1, h: -1 },
    iconScale: 1,
    iconRotation: 0,
  },
  // Auto-spin mode multipliers (x2, x4, x6, x10)
  x2_auto_default: {
    iconAsset: 'i65_x2',
    icon: { x: -1, y: -1, w: -1, h: -1 },
    iconScale: 1,
    iconRotation: 0,
  },
  x2_auto_active: {
    iconAsset: 'i64_x2',
    icon: { x: -1, y: -1, w: -1, h: -1 },
    iconScale: 1,
    iconRotation: 0,
  },
  x4_auto_default: {
    iconAsset: 'i65_x4',
    icon: { x: -1, y: -1, w: -1, h: -1 },
    iconScale: 1,
    iconRotation: 0,
  },
  x4_auto_active: {
    iconAsset: 'i64_x4',
    icon: { x: -1, y: -1, w: -1, h: -1 },
    iconScale: 1,
    iconRotation: 0,
  },
  x6_auto_default: {
    iconAsset: 'i65_x6',
    icon: { x: -1, y: -1, w: -1, h: -1 },
    iconScale: 1,
    iconRotation: 0,
  },
  x6_auto_active: {
    iconAsset: 'i64_x6',
    icon: { x: -1, y: -1, w: -1, h: -1 },
    iconScale: 1,
    iconRotation: 0,
  },
  x10_auto_default: {
    iconAsset: 'i65_x10',
    icon: { x: -1, y: -1, w: -1, h: -1 },
    iconScale: 1,
    iconRotation: 0,
  },
  x10_auto_active: {
    iconAsset: 'i64_x10',
    icon: { x: -1, y: -1, w: -1, h: -1 },
    iconScale: 1,
    iconRotation: 0,
  },
  page_title: {
    iconAsset: 'i58_03',
    icon: { x: -1, y: -1, w: -1, h: -1 },
    iconScale: 0.72,
    iconRotation: 0,
  },
  bg_01: {
    iconAsset: 'i43_02',
    icon: { x: -1, y: -1, w: -1, h: -1 },
    iconScale: 0.7,
    iconRotation: -Math.PI / 2,
  },
  bg_02: {
    iconAsset: 'i43_05',
    icon: { x: -1, y: -1, w: -1, h: -1 },
    iconScale: 1,
    iconRotation: -Math.PI / 2,
  },
  bg_03: {
    iconAsset: 'i43_07',
    icon: { x: -1, y: -1, w: -1, h: -1 },
    iconScale: 1,
    iconRotation: 0,
  },
};
