export const ASSETS = {
  imagePaths: {
    start_background: new URL('../assets/start_game_bg.jpg', import.meta.url).href,

    // Individual tile images
    tile_bai: new URL('../assets/slotMachine/tiles/tile_bai.png', import.meta.url).href,
    tile_bai_gold: new URL('../assets/slotMachine/tiles/tile_bai_gold.png', import.meta.url).href,
    tile_bawan: new URL('../assets/slotMachine/tiles/tile_bawan.png', import.meta.url).href,
    tile_bawan_gold: new URL('../assets/slotMachine/tiles/tile_bawan_gold.png', import.meta.url).href,
    tile_bonus: new URL('../assets/slotMachine/tiles/tile_bonus.png', import.meta.url).href,
    tile_fa: new URL('../assets/slotMachine/tiles/tile_fa.png', import.meta.url).href,
    tile_fa_gold: new URL('../assets/slotMachine/tiles/tile_fa_gold.png', import.meta.url).href,
    tile_wild: new URL('../assets/slotMachine/tiles/tile_gold.png', import.meta.url).href,
    tile_liangsuo: new URL('../assets/slotMachine/tiles/tile_liangsuo.png', import.meta.url).href,
    tile_liangsuo_gold: new URL('../assets/slotMachine/tiles/tile_liangsuo_gold.png', import.meta.url).href,
    tile_liangtong: new URL('../assets/slotMachine/tiles/tile_liangtong.png', import.meta.url).href,
    tile_liangtong_gold: new URL('../assets/slotMachine/tiles/tile_liangtong_gold.png', import.meta.url).href,
    tile_wusuo: new URL('../assets/slotMachine/tiles/tile_wusuo.png', import.meta.url).href,
    tile_wusuo_gold: new URL('../assets/slotMachine/tiles/tile_wusuo_gold.png', import.meta.url).href,
    tile_wutong: new URL('../assets/slotMachine/tiles/tile_wutong.png', import.meta.url).href,
    tile_wutong_gold: new URL('../assets/slotMachine/tiles/tile_wutong_gold.png', import.meta.url).href,
    tile_zhong: new URL('../assets/slotMachine/tiles/tile_zhong.png', import.meta.url).href,
    tile_zhong_gold: new URL('../assets/slotMachine/tiles/tile_zhong_gold.png', import.meta.url).href,

    // Effects
    effect_star: new URL('../assets/slotMachine/effects/effect_star.png', import.meta.url).href,
    effect_golden_light_burst: new URL('../assets/slotMachine/effects/effect_golden_light_burst.png', import.meta.url).href,

    // Winning announcements
    win_bg: new URL('../assets/slotMachine/winAnnouncements/bg.png', import.meta.url).href,
    win_small: new URL('../assets/slotMachine/winAnnouncements/small.png', import.meta.url).href,
    win_grand: new URL('../assets/slotMachine/winAnnouncements/grand.png', import.meta.url).href,
    win_mega: new URL('../assets/slotMachine/winAnnouncements/mega.png', import.meta.url).href,
    win_megagrand: new URL('../assets/slotMachine/winAnnouncements/mega_grand.png', import.meta.url).href,
    win_jackpot: new URL('../assets/slotMachine/winAnnouncements/jackpot.png', import.meta.url).href,
    jackpot_begin_bg: new URL('../assets/slotMachine/winAnnouncements/jackpot_begin_bg.png', import.meta.url).href,
    win_gold: new URL('../assets/slotMachine/winAnnouncements/gold.png', import.meta.url).href,

    // New icons
    icon_plus: new URL('../assets/slotMachine/icons/icon_plus.png', import.meta.url).href,
    icon_minus: new URL('../assets/slotMachine/icons/icon_minus.png', import.meta.url).href,
    icon_close: new URL('../assets/slotMachine/icons/icon_close.png', import.meta.url).href,
    icon_volume_on: new URL('../assets/slotMachine/icons/icon_volume_on.png', import.meta.url).href,
    icon_volume_off: new URL('../assets/slotMachine/icons/icon_volume_off.png', import.meta.url).href,
    icon_menu: new URL('../assets/slotMachine/icons/icon_menu.png', import.meta.url).href,
    icon_paytable: new URL('../assets/slotMachine/icons/icon_paytable.png', import.meta.url).href,
    icon_menu_mute: new URL('../assets/slotMachine/icons/icon_menu_mute.png', import.meta.url).href,
    icon_rules: new URL('../assets/slotMachine/icons/icon_rules.png', import.meta.url).href,
    icon_exit: new URL('../assets/slotMachine/icons/icon_exit.png', import.meta.url).href,
    icon_spin_arrows_small: new URL('../assets/slotMachine/icons/icon_spin_arrows_small.png', import.meta.url).href,
    icon_turbo: new URL('../assets/slotMachine/icons/icon_turbo.png', import.meta.url).href,
    icon_wallet: new URL('../assets/slotMachine/icons/icon_wallet.png', import.meta.url).href,
    icon_play: new URL('../assets/slotMachine/icons/icon_play.png', import.meta.url).href,
    icon_spin_square_bg: new URL('../assets/slotMachine/icons/icon_spin_square_bg.png', import.meta.url).href,
    icon_spin_circle_bg: new URL('../assets/slotMachine/icons/icon_spin_circle_bg.png', import.meta.url).href,
    icon_spin_arrows_normal: new URL('../assets/slotMachine/icons/icon_spin_arrows_normal.png', import.meta.url).href,
    icon_spin_arrows_normal_blur: new URL('../assets/slotMachine/icons/icon_spin_arrows_normal_blur.png', import.meta.url).href,
    icon_spin_arrows_disabled_blur: new URL('../assets/slotMachine/icons/icon_spin_arrows_disabled_blur.png', import.meta.url).href,
    icon_spin_arrows_disabled: new URL('../assets/slotMachine/icons/icon_spin_arrows_disabled.png', import.meta.url).href,
    icon_history_active_large: new URL('../assets/slotMachine/icons/icon_history_active_large.png', import.meta.url).href,
    icon_circle_auto: new URL('../assets/slotMachine/icons/icon_circle_auto.png', import.meta.url).href,
    icon_circle_history: new URL('../assets/slotMachine/icons/icon_circle_history.png', import.meta.url).href,
    icon_coin: new URL('../assets/slotMachine/icons/icon_coin.png', import.meta.url).href,
    icon_history_active_small: new URL('../assets/slotMachine/icons/icon_history_active_small.png', import.meta.url).href,

    // Glyphs for numbers and text
    glyph_0_gold_small: new URL('../assets/slotMachine/glyphs/glyph_0_gold_small.png', import.meta.url).href,
    glyph_1_gold_small: new URL('../assets/slotMachine/glyphs/glyph_1_gold_small.png', import.meta.url).href,
    glyph_2_gold_small: new URL('../assets/slotMachine/glyphs/glyph_2_gold_small.png', import.meta.url).href,
    glyph_3_gold_small: new URL('../assets/slotMachine/glyphs/glyph_3_gold_small.png', import.meta.url).href,
    glyph_4_gold_small: new URL('../assets/slotMachine/glyphs/glyph_4_gold_small.png', import.meta.url).href,
    glyph_5_gold_small: new URL('../assets/slotMachine/glyphs/glyph_5_gold_small.png', import.meta.url).href,
    glyph_6_gold_small: new URL('../assets/slotMachine/glyphs/glyph_6_gold_small.png', import.meta.url).href,
    glyph_7_gold_small: new URL('../assets/slotMachine/glyphs/glyph_7_gold_small.png', import.meta.url).href,
    glyph_8_gold_small: new URL('../assets/slotMachine/glyphs/glyph_8_gold_small.png', import.meta.url).href,
    glyph_9_gold_small: new URL('../assets/slotMachine/glyphs/glyph_9_gold_small.png', import.meta.url).href,
    glyph_dot_gold_small: new URL('../assets/slotMachine/glyphs/glyph_dot_gold_small.png', import.meta.url).href,
    glyph_comma_gold_small: new URL('../assets/slotMachine/glyphs/glyph_comma_gold_small.png', import.meta.url).href,
    glyph_x_gold_small: new URL('../assets/slotMachine/glyphs/glyph_x_gold_small.png', import.meta.url).href,
    glyph_0_gold_large: new URL('../assets/slotMachine/glyphs/glyph_0_gold_large.png', import.meta.url).href,
    glyph_1_gold_large: new URL('../assets/slotMachine/glyphs/glyph_1_gold_large.png', import.meta.url).href,
    glyph_2_gold_large: new URL('../assets/slotMachine/glyphs/glyph_2_gold_large.png', import.meta.url).href,
    glyph_3_gold_large: new URL('../assets/slotMachine/glyphs/glyph_3_gold_large.png', import.meta.url).href,
    glyph_4_gold_large: new URL('../assets/slotMachine/glyphs/glyph_4_gold_large.png', import.meta.url).href,
    glyph_5_gold_large: new URL('../assets/slotMachine/glyphs/glyph_5_gold_large.png', import.meta.url).href,
    glyph_6_gold_large: new URL('../assets/slotMachine/glyphs/glyph_6_gold_large.png', import.meta.url).href,
    glyph_7_gold_large: new URL('../assets/slotMachine/glyphs/glyph_7_gold_large.png', import.meta.url).href,
    glyph_8_gold_large: new URL('../assets/slotMachine/glyphs/glyph_8_gold_large.png', import.meta.url).href,
    glyph_9_gold_large: new URL('../assets/slotMachine/glyphs/glyph_9_gold_large.png', import.meta.url).href,
    glyph_dot_gold_large: new URL('../assets/slotMachine/glyphs/glyph_dot_gold_large.png', import.meta.url).href,
    glyph_comma_gold_large: new URL('../assets/slotMachine/glyphs/glyph_comma_gold_large.png', import.meta.url).href,
    glyph_free_spin_text: new URL('../assets/slotMachine/glyphs/glyph_free_spin_text.png', import.meta.url).href,
    glyph_spin_last_text: new URL('../assets/slotMachine/glyphs/glyph_spin_last_text.png', import.meta.url).href,
    glyph_win_1024_text: new URL('../assets/slotMachine/glyphs/glyph_win_1024_text.png', import.meta.url).href,
    glyph_1024_ways_text: new URL('../assets/slotMachine/glyphs/glyph_1024_ways_text.png', import.meta.url).href,
    glyph_bonus_12_free_text: new URL('../assets/slotMachine/glyphs/glyph_bonus_12_free_text.png', import.meta.url).href,
    glyph_gold_symbol_chance_text: new URL('../assets/slotMachine/glyphs/glyph_gold_symbol_chance_text.png', import.meta.url).href,
    glyph_free_spin_10x_text: new URL('../assets/slotMachine/glyphs/glyph_free_spin_10x_text.png', import.meta.url).href,
    glyph_win_text: new URL('../assets/slotMachine/glyphs/glyph_win_text.png', import.meta.url).href,
    glyph_total_win_text: new URL('../assets/slotMachine/glyphs/glyph_total_win_text.png', import.meta.url).href,
    glyph_x1_gold: new URL('../assets/slotMachine/glyphs/glyph_x1_gold.png', import.meta.url).href,
    glyph_x2_gold: new URL('../assets/slotMachine/glyphs/glyph_x2_gold.png', import.meta.url).href,
    glyph_x3_gold: new URL('../assets/slotMachine/glyphs/glyph_x3_gold.png', import.meta.url).href,
    glyph_x4_gold: new URL('../assets/slotMachine/glyphs/glyph_x4_gold.png', import.meta.url).href,
    glyph_x5_gold: new URL('../assets/slotMachine/glyphs/glyph_x5_gold.png', import.meta.url).href,
    glyph_x6_gold: new URL('../assets/slotMachine/glyphs/glyph_x6_gold.png', import.meta.url).href,
    glyph_x10_gold: new URL('../assets/slotMachine/glyphs/glyph_x10_gold.png', import.meta.url).href,
    glyph_x1_brown: new URL('../assets/slotMachine/glyphs/glyph_x1_brown.png', import.meta.url).href,
    glyph_x2_brown: new URL('../assets/slotMachine/glyphs/glyph_x2_brown.png', import.meta.url).href,
    glyph_x2_red: new URL('../assets/slotMachine/glyphs/glyph_x2_red.png', import.meta.url).href,
    glyph_x3_brown: new URL('../assets/slotMachine/glyphs/glyph_x3_brown.png', import.meta.url).href,
    glyph_x4_red: new URL('../assets/slotMachine/glyphs/glyph_x4_red.png', import.meta.url).href,
    glyph_x5_brown: new URL('../assets/slotMachine/glyphs/glyph_x5_brown.png', import.meta.url).href,
    glyph_x6_red: new URL('../assets/slotMachine/glyphs/glyph_x6_red.png', import.meta.url).href,
    glyph_x10_red: new URL('../assets/slotMachine/glyphs/glyph_x10_red.png', import.meta.url).href,

    // Background images
    background_marquee_green: new URL('../assets/slotMachine/background/background_marquee_green.png', import.meta.url).href,
    background_marquee_purple: new URL('../assets/slotMachine/background/background_marquee_purple.png', import.meta.url).href,
    background_marquee_red: new URL('../assets/slotMachine/background/background_marquee_red.png', import.meta.url).href,
    background_vertical_coins: new URL('../assets/slotMachine/background/background_vertical_coins.png', import.meta.url).href,
    background_coins: new URL('../assets/slotMachine/background/background_coins.png', import.meta.url).href,
    background_vertical_wood: new URL('../assets/slotMachine/background/background_vertical_wood.png', import.meta.url).href,
    background_top_icons: new URL('../assets/slotMachine/background/background_top_icons.png', import.meta.url).href,
    background_bottom: new URL('../assets/slotMachine/background/background_bottom.png', import.meta.url).href,

    // Header consecutive wins background
    active_status_bg: new URL('../assets/consecutiveWins/active_status_bg.png', import.meta.url).href,
  },
  loadedImages: {},
  videoPaths: {
    jackpot: new URL('../assets/videos/jackpot.mp4', import.meta.url).href,
    jackpot_result: new URL('../assets/videos/jackpot_result.mp4', import.meta.url).href
  },
  audioPaths: {
    background_music: new URL('../assets/audio/background_music.mp3', import.meta.url).href,
    background_music_jackpot: new URL('../assets/audio/background_music_jackpot.mp3', import.meta.url).href,
    game_start: new URL('../assets/audio/game_start.mp3', import.meta.url).href,
    consecutive_wins_2x: new URL('../assets/audio/consecutive_wins/2x.mp3', import.meta.url).href,
    consecutive_wins_3x: new URL('../assets/audio/consecutive_wins/3x.mp3', import.meta.url).href,
    consecutive_wins_4x: new URL('../assets/audio/consecutive_wins/4x.mp3', import.meta.url).href,
    consecutive_wins_5x: new URL('../assets/audio/consecutive_wins/5x.mp3', import.meta.url).href,
    consecutive_wins_6x: new URL('../assets/audio/consecutive_wins/6x.mp3', import.meta.url).href,
    consecutive_wins_10x: new URL('../assets/audio/consecutive_wins/10x.mp3', import.meta.url).href,
    // Win sounds for specific symbols
    win_bai: new URL('../assets/audio/wins/bai.mp3', import.meta.url).href,
    win_zhong: new URL('../assets/audio/wins/zhong.mp3', import.meta.url).href,
    win_fa: new URL('../assets/audio/wins/fa.mp3', import.meta.url).href,
    win_liangsuo: new URL('../assets/audio/wins/liangsuo.mp3', import.meta.url).href,
    win_liangtong: new URL('../assets/audio/wins/liangtong.mp3', import.meta.url).href,
    win_wusuo: new URL('../assets/audio/wins/wusuo.mp3', import.meta.url).href,
    win_wutong: new URL('../assets/audio/wins/wutong.mp3', import.meta.url).href,
    win_bawan: new URL('../assets/audio/wins/bawan.mp3', import.meta.url).href,
    win_all_boy: new URL('../assets/audio/wins/all_boy_sound.mp3', import.meta.url).href,
    win_all_girl: new URL('../assets/audio/wins/all_girl_sound.mp3', import.meta.url).href,
    win_megagrand: new URL('../assets/audio/wins/jackpot.mp3', import.meta.url).href,
    winning_announcement: new URL('../assets/audio/wins/winning_announcement.mp3', import.meta.url).href,
    winning_highlight: new URL('../assets/audio/wins/winning_highlight.mp3', import.meta.url).href,
    background_noises: [
      new URL('../assets/audio/background_noise/noise_1.mp3', import.meta.url).href,
      new URL('../assets/audio/background_noise/noise_2.mp3', import.meta.url).href,
      new URL('../assets/audio/background_noise/noise_3.mp3', import.meta.url).href,
      new URL('../assets/audio/background_noise/noise_4.mp3', import.meta.url).href,
      new URL('../assets/audio/background_noise/noise_5.mp3', import.meta.url).href,
      new URL('../assets/audio/background_noise/noise_6.mp3', import.meta.url).href,
      new URL('../assets/audio/background_noise/noise_7.mp3', import.meta.url).href,
      new URL('../assets/audio/background_noise/noise_8.mp3', import.meta.url).href,
      new URL('../assets/audio/background_noise/noise_9.mp3', import.meta.url).href,
      new URL('../assets/audio/background_noise/noise_10.mp3', import.meta.url).href,
      new URL('../assets/audio/background_noise/noise_11.mp3', import.meta.url).href
    ],
    //effect
    lot: new URL('../assets/audio/effect/lot.m4a', import.meta.url).href,
    reel_spin: new URL('../assets/audio/effect/reel_spin.m4a', import.meta.url).href,
    reel_spin_stop: new URL('../assets/audio/effect/reel_spin_stop.m4a', import.meta.url).href,
    reach_bonus: new URL('../assets/audio/effect/reach_bonus.m4a', import.meta.url).href,
    jackpot_finalize: new URL('../assets/audio/jackpot_finalize.m4a', import.meta.url).href
  }
}
