export const ASSETS = {
  imagePaths: {
    start_background: new URL('../assets/start_game_bg.jpg', import.meta.url).href,
    // Spin button assets: frame background + gold arrow
    spin: new URL('../assets/slotMachine/spin_btn/spinBtn.png', import.meta.url).href,
    // Individual tile images
    tile_bai: new URL('../assets/slotMachine/tiles/bai.png', import.meta.url).href,
    tile_bai_gold: new URL('../assets/slotMachine/tiles/bai_gold.png', import.meta.url).href,
    tile_bawan: new URL('../assets/slotMachine/tiles/bawan.png', import.meta.url).href,
    tile_bawan_gold: new URL('../assets/slotMachine/tiles/bawan_gold.png', import.meta.url).href,
    tile_bonus: new URL('../assets/slotMachine/tiles/bonus.png', import.meta.url).href,
    tile_fa: new URL('../assets/slotMachine/tiles/fa.png', import.meta.url).href,
    tile_fa_gold: new URL('../assets/slotMachine/tiles/fa_gold.png', import.meta.url).href,
    tile_gold: new URL('../assets/slotMachine/tiles/gold.png', import.meta.url).href,
    tile_liangsuo: new URL('../assets/slotMachine/tiles/liangsuo.png', import.meta.url).href,
    tile_liangsuo_gold: new URL('../assets/slotMachine/tiles/liangsuo_gold.png', import.meta.url).href,
    tile_liangtong: new URL('../assets/slotMachine/tiles/liangtong.png', import.meta.url).href,
    tile_liangtong_gold: new URL('../assets/slotMachine/tiles/liangtong_gold.png', import.meta.url).href,
    tile_wusuo: new URL('../assets/slotMachine/tiles/wusuo.png', import.meta.url).href,
    tile_wusuo_gold: new URL('../assets/slotMachine/tiles/wusuo_gold.png', import.meta.url).href,
    tile_wutong: new URL('../assets/slotMachine/tiles/wutong.png', import.meta.url).href,
    tile_wutong_gold: new URL('../assets/slotMachine/tiles/wutong_gold.png', import.meta.url).href,
    tile_zhong: new URL('../assets/slotMachine/tiles/zhong.png', import.meta.url).href,
    tile_zhong_gold: new URL('../assets/slotMachine/tiles/zhong_gold.png', import.meta.url).href,
    tiles_star: new URL('../assets/slotMachine/tiles/star.png', import.meta.url).href,
    // Consecutive wins spritesheets
    header_multiplier_active: new URL('../assets/consecutiveWins/64.png', import.meta.url).href,
    header_multiplier_default: new URL('../assets/consecutiveWins/65.png', import.meta.url).href,
    active_status_bg: new URL('../assets/consecutiveWins/active_status_bg.png', import.meta.url).href,
    // Footer
    footer_bg: new URL('../assets/footer_bg.png', import.meta.url).href,
    footer_notification_bg: new URL('../assets/notification_bg.png', import.meta.url).href,
    footer_notification_text: new URL('../assets/notification_text.png', import.meta.url).href,
    footer_icon_setting: new URL('../assets/6.png', import.meta.url).href,
    footer_icon_setting1: new URL('../assets/46.png', import.meta.url).href,
    // Winning announcements
    win_bg: new URL('../assets/slotMachine/winAnnouncements/bg.png', import.meta.url).href,
    win_small: new URL('../assets/slotMachine/winAnnouncements/small.png', import.meta.url).href,
    win_grand: new URL('../assets/slotMachine/winAnnouncements/grand.png', import.meta.url).href,
    win_mega: new URL('../assets/slotMachine/winAnnouncements/mega.png', import.meta.url).href,
    win_jackpot: new URL('../assets/slotMachine/winAnnouncements/jackpot.png', import.meta.url).href,
    win_gold: new URL('../assets/slotMachine/winAnnouncements/gold.png', import.meta.url).href,

    // New icons
    i6_03: new URL('../assets/images/6_03.png', import.meta.url).href,
    i6_04: new URL('../assets/images/6_04.png', import.meta.url).href,
    i6_05: new URL('../assets/images/6_05.png', import.meta.url).href,
    i6_06: new URL('../assets/images/6_06.png', import.meta.url).href,
    i6_18: new URL('../assets/images/6_18.png', import.meta.url).href,
    i6_22: new URL('../assets/images/6_22.png', import.meta.url).href,
    i6_30: new URL('../assets/images/6_30.png', import.meta.url).href,
    i6_31: new URL('../assets/images/6_31.png', import.meta.url).href,
    i6_34: new URL('../assets/images/6_34.png', import.meta.url).href,
    i6_36: new URL('../assets/images/6_36.png', import.meta.url).href,
    i6_38: new URL('../assets/images/6_38.png', import.meta.url).href,
    i6_40: new URL('../assets/images/6_40.png', import.meta.url).href,
    i6_43: new URL('../assets/images/6_43.png', import.meta.url).href,
    i6_45: new URL('../assets/images/6_45.png', import.meta.url).href,
    i17_01: new URL('../assets/images/17_01.png', import.meta.url).href,
    i17_02: new URL('../assets/images/17_02.png', import.meta.url).href,
    i17_03: new URL('../assets/images/17_03.png', import.meta.url).href,
    i17_04: new URL('../assets/images/17_04.png', import.meta.url).href,
    i17_05: new URL('../assets/images/17_05.png', import.meta.url).href,
    i17_06: new URL('../assets/images/17_06.png', import.meta.url).href,
    i25_03: new URL('../assets/images/25_03.png', import.meta.url).href,
    i43_03: new URL('../assets/images/43_03.png', import.meta.url).href,
    i43_08: new URL('../assets/images/43_08.png', import.meta.url).href,
    i46_01: new URL('../assets/images/46_01.png', import.meta.url).href,
    i46_02: new URL('../assets/images/46_02.png', import.meta.url).href,
    i46_04: new URL('../assets/images/46_04.png', import.meta.url).href,
    i46_06: new URL('../assets/images/46_06.png', import.meta.url).href,
    i46_07: new URL('../assets/images/46_07.png', import.meta.url).href,
    i58_01: new URL('../assets/images/58_01.png', import.meta.url).href,
    i58_06: new URL('../assets/images/58_06.png', import.meta.url).href,
    i58_07: new URL('../assets/images/58_07.png', import.meta.url).href,
    i58_08: new URL('../assets/images/58_08.png', import.meta.url).href,
  },
  loadedImages: {},
  audioPaths: {
    background_music: new URL('../assets/audio/background_music.mp3', import.meta.url).href,
    game_start: new URL('../assets/audio/game_start.mp3', import.meta.url).href,
    consecutive_wins_2x: new URL('../assets/audio/consecutive_wins/2x.mp3', import.meta.url).href,
    consecutive_wins_3x: new URL('../assets/audio/consecutive_wins/3x.mp3', import.meta.url).href,
    consecutive_wins_5x: new URL('../assets/audio/consecutive_wins/5x.mp3', import.meta.url).href,
    background_noises: [
      new URL('../assets/audio/background_noise/noise_1.mp3', import.meta.url).href,
      new URL('../assets/audio/background_noise/noise_2.mp3', import.meta.url).href,
      new URL('../assets/audio/background_noise/noise_3.mp3', import.meta.url).href,
      new URL('../assets/audio/background_noise/noise_4.mp3', import.meta.url).href,
      new URL('../assets/audio/background_noise/noise_5.mp3', import.meta.url).href,
      new URL('../assets/audio/background_noise/noise_6.mp3', import.meta.url).href,
      new URL('../assets/audio/background_noise/noise_7.mp3', import.meta.url).href,
      new URL('../assets/audio/background_noise/noise_8.mp3', import.meta.url).href,
      new URL('../assets/audio/background_noise/noise_9.mp3', import.meta.url).href,
      new URL('../assets/audio/background_noise/noise_10.mp3', import.meta.url).href,
      new URL('../assets/audio/background_noise/noise_11.mp3', import.meta.url).href
    ]
  }
}
