export const ASSETS = {
  imagePaths: {
    start_background: new URL('../assets/start_game_bg.jpg', import.meta.url).href,
    // Individual tile images
    tile_bai: new URL('../assets/slotMachine/tiles/bai.png', import.meta.url).href,
    tile_bai_gold: new URL('../assets/slotMachine/tiles/bai_gold.png', import.meta.url).href,
    tile_bawan: new URL('../assets/slotMachine/tiles/bawan.png', import.meta.url).href,
    tile_bawan_gold: new URL('../assets/slotMachine/tiles/bawan_gold.png', import.meta.url).href,
    tile_bonus: new URL('../assets/slotMachine/tiles/bonus.png', import.meta.url).href,
    tile_fa: new URL('../assets/slotMachine/tiles/fa.png', import.meta.url).href,
    tile_fa_gold: new URL('../assets/slotMachine/tiles/fa_gold.png', import.meta.url).href,
    tile_wild: new URL('../assets/slotMachine/tiles/gold.png', import.meta.url).href,
    tile_liangsuo: new URL('../assets/slotMachine/tiles/liangsuo.png', import.meta.url).href,
    tile_liangsuo_gold: new URL('../assets/slotMachine/tiles/liangsuo_gold.png', import.meta.url).href,
    tile_liangtong: new URL('../assets/slotMachine/tiles/liangtong.png', import.meta.url).href,
    tile_liangtong_gold: new URL('../assets/slotMachine/tiles/liangtong_gold.png', import.meta.url).href,
    tile_wusuo: new URL('../assets/slotMachine/tiles/wusuo.png', import.meta.url).href,
    tile_wusuo_gold: new URL('../assets/slotMachine/tiles/wusuo_gold.png', import.meta.url).href,
    tile_wutong: new URL('../assets/slotMachine/tiles/wutong.png', import.meta.url).href,
    tile_wutong_gold: new URL('../assets/slotMachine/tiles/wutong_gold.png', import.meta.url).href,
    tile_zhong: new URL('../assets/slotMachine/tiles/zhong.png', import.meta.url).href,
    tile_zhong_gold: new URL('../assets/slotMachine/tiles/zhong_gold.png', import.meta.url).href,
    tiles_star: new URL('../assets/slotMachine/tiles/star.png', import.meta.url).href,
    // Winning announcements
    win_bg: new URL('../assets/slotMachine/winAnnouncements/bg.png', import.meta.url).href,
    win_small: new URL('../assets/slotMachine/winAnnouncements/small.png', import.meta.url).href,
    win_grand: new URL('../assets/slotMachine/winAnnouncements/grand.png', import.meta.url).href,
    win_mega: new URL('../assets/slotMachine/winAnnouncements/mega.png', import.meta.url).href,
    win_jackpot: new URL('../assets/slotMachine/winAnnouncements/jackpot.png', import.meta.url).href,
    win_gold: new URL('../assets/slotMachine/winAnnouncements/gold.png', import.meta.url).href,

    // New icons
    i6_03: new URL('../assets/images/6_03.png', import.meta.url).href,
    i6_04: new URL('../assets/images/6_04.png', import.meta.url).href,
    i6_05: new URL('../assets/images/6_05.png', import.meta.url).href,
    i6_06: new URL('../assets/images/6_06.png', import.meta.url).href,
    i6_18: new URL('../assets/images/6_18.png', import.meta.url).href,
    i6_22: new URL('../assets/images/6_22.png', import.meta.url).href,
    i6_30: new URL('../assets/images/6_30.png', import.meta.url).href,
    i6_31: new URL('../assets/images/6_31.png', import.meta.url).href,
    i6_34: new URL('../assets/images/6_34.png', import.meta.url).href,
    i6_36: new URL('../assets/images/6_36.png', import.meta.url).href,
    i6_38: new URL('../assets/images/6_38.png', import.meta.url).href,
    i6_40: new URL('../assets/images/6_40.png', import.meta.url).href,
    i6_43: new URL('../assets/images/6_43.png', import.meta.url).href,
    i6_45: new URL('../assets/images/6_45.png', import.meta.url).href,
    i17_01: new URL('../assets/images/17_01.png', import.meta.url).href,
    i17_02: new URL('../assets/images/17_02.png', import.meta.url).href,
    i17_03: new URL('../assets/images/17_03.png', import.meta.url).href,
    i17_04: new URL('../assets/images/17_04.png', import.meta.url).href,
    i17_05: new URL('../assets/images/17_05.png', import.meta.url).href,
    i17_06: new URL('../assets/images/17_06.png', import.meta.url).href,
    i25_03: new URL('../assets/images/25_03.png', import.meta.url).href,
    i43_02: new URL('../assets/images/43_02.png', import.meta.url).href,
    i43_03: new URL('../assets/images/43_03.png', import.meta.url).href,
    i43_05: new URL('../assets/images/43_05.png', import.meta.url).href,
    i43_07: new URL('../assets/images/43_07.png', import.meta.url).href,
    i43_08: new URL('../assets/images/43_08.png', import.meta.url).href,
    i46_01: new URL('../assets/images/46_01.png', import.meta.url).href,
    i46_02: new URL('../assets/images/46_02.png', import.meta.url).href,
    i46_04: new URL('../assets/images/46_04.png', import.meta.url).href,
    i46_06: new URL('../assets/images/46_06.png', import.meta.url).href,
    i46_07: new URL('../assets/images/46_07.png', import.meta.url).href,
    i58_01: new URL('../assets/images/58_01.png', import.meta.url).href,
    i58_03: new URL('../assets/images/58_03.png', import.meta.url).href,
    i58_06: new URL('../assets/images/58_06.png', import.meta.url).href,
    i58_07: new URL('../assets/images/58_07.png', import.meta.url).href,
    i58_08: new URL('../assets/images/58_08.png', import.meta.url).href,
    i64_x1: new URL('../assets/images/64_x1.png', import.meta.url).href,
    i64_x2: new URL('../assets/images/64_x2.png', import.meta.url).href,
    i64_x3: new URL('../assets/images/64_x3.png', import.meta.url).href,
    i64_x4: new URL('../assets/images/64_x4.png', import.meta.url).href,
    i64_x5: new URL('../assets/images/64_x5.png', import.meta.url).href,
    i64_x6: new URL('../assets/images/64_x6.png', import.meta.url).href,
    i64_x10: new URL('../assets/images/64_x10.png', import.meta.url).href,
    i65_x1: new URL('../assets/images/65_x1.png', import.meta.url).href,
    i65_x2: new URL('../assets/images/65_x2.png', import.meta.url).href,
    i65_x2_free: new URL('../assets/images/65_x2_free.png', import.meta.url).href,
    i65_x3: new URL('../assets/images/65_x3.png', import.meta.url).href,
    i65_x4: new URL('../assets/images/65_x4.png', import.meta.url).href,
    i65_x5: new URL('../assets/images/65_x5.png', import.meta.url).href,
    i65_x6: new URL('../assets/images/65_x6.png', import.meta.url).href,
    i65_x10: new URL('../assets/images/65_x10.png', import.meta.url).href,
  },
  loadedImages: {},
  audioPaths: {
    background_music: new URL('../assets/audio/background_music.mp3', import.meta.url).href,
    game_start: new URL('../assets/audio/game_start.mp3', import.meta.url).href,
    consecutive_wins_2x: new URL('../assets/audio/consecutive_wins/2x.mp3', import.meta.url).href,
    consecutive_wins_3x: new URL('../assets/audio/consecutive_wins/3x.mp3', import.meta.url).href,
    consecutive_wins_5x: new URL('../assets/audio/consecutive_wins/5x.mp3', import.meta.url).href,
    // Win sounds for specific symbols
    win_bai: new URL('../assets/audio/wins/bai.mp3', import.meta.url).href,
    win_zhong: new URL('../assets/audio/wins/zhong.mp3', import.meta.url).href,
    win_fa: new URL('../assets/audio/wins/fa.mp3', import.meta.url).href,
    win_liangsuo: new URL('../assets/audio/wins/liangsuo.mp3', import.meta.url).href,
    win_liangtong: new URL('../assets/audio/wins/liangtong.mp3', import.meta.url).href,
    win_wusuo: new URL('../assets/audio/wins/wusuo.mp3', import.meta.url).href,
    win_wutong: new URL('../assets/audio/wins/wutong.mp3', import.meta.url).href,
    win_bawan: new URL('../assets/audio/wins/bawan.mp3', import.meta.url).href,
    win_all_boy: new URL('../assets/audio/wins/all_boy_sound.mp3', import.meta.url).href,
    win_all_girl: new URL('../assets/audio/wins/all_girl_sound.mp3', import.meta.url).href,
    win_jackpot: new URL('../assets/audio/wins/jackpot.mp3', import.meta.url).href,
    winning_announcement: new URL('../assets/audio/wins/winning_announcement.mp3', import.meta.url).href,
    background_noises: [
      new URL('../assets/audio/background_noise/noise_1.mp3', import.meta.url).href,
      new URL('../assets/audio/background_noise/noise_2.mp3', import.meta.url).href,
      new URL('../assets/audio/background_noise/noise_3.mp3', import.meta.url).href,
      new URL('../assets/audio/background_noise/noise_4.mp3', import.meta.url).href,
      new URL('../assets/audio/background_noise/noise_5.mp3', import.meta.url).href,
      new URL('../assets/audio/background_noise/noise_6.mp3', import.meta.url).href,
      new URL('../assets/audio/background_noise/noise_7.mp3', import.meta.url).href,
      new URL('../assets/audio/background_noise/noise_8.mp3', import.meta.url).href,
      new URL('../assets/audio/background_noise/noise_9.mp3', import.meta.url).href,
      new URL('../assets/audio/background_noise/noise_10.mp3', import.meta.url).href,
      new URL('../assets/audio/background_noise/noise_11.mp3', import.meta.url).href
    ],
    //effect
    lot: new URL('../assets/audio/effect/lot.m4a', import.meta.url).href,
    reel_spin: new URL('../assets/audio/effect/reel_spin.m4a', import.meta.url).href,
    reel_spin_stop: new URL('../assets/audio/effect/reel_spin_stop.m4a', import.meta.url).href,
    reach_bonus: new URL('../assets/audio/effect/reach_bonus.m4a', import.meta.url).href
  }
}
